version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: gestaobiblioteca_db
    environment:
      POSTGRES_DB: gestaobiblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestaobiblioteca_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestaobiblioteca
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./src/main/frontend
      dockerfile: Dockerfile
    container_name: gestaobiblioteca_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: gestaobiblioteca_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
